---
description: 
pack: aws
enabled: true
entry_point: run.py
name: apigateway_update_deployment
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: update_deployment
    immutable: true
    type: string
  cls:
    default: apigateway
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  restApiId:
    type: string
    description: "The replacement identifier of the RestApi resource for the Deployment resource to change information about."
    required: true
  deploymentId:
    type: string
    description: "The replacement identifier for the Deployment resource to change information about."
    required: true
  patchOperations:
    type: array
    description: "A list of update operations to be applied to the specified resource and in the order specified in this list."