---
description: 
pack: aws
enabled: true
entry_point: run.py
name: apigateway_create_deployment
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: create_deployment
    immutable: true
    type: string
  cls:
    default: apigateway
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  restApiId:
    type: string
    description: "The RestApi resource identifier for the Deployment resource to create."
    required: true
  stageName:
    type: string
    description: "The name of the Stage resource for the Deployment resource to create."
  stageDescription:
    type: string
    description: "The description of the Stage resource for the Deployment resource to create."
  description:
    type: string
    description: "The description for the Deployment resource to create."
  cacheClusterEnabled:
    type: boolean
    description: "Enables a cache cluster for the Stage resource specified in the input."
  cacheClusterSize:
    type: string
    description: "Specifies the cache cluster size for the Stage resource specified in the input, if a cache cluster is enabled."
  variables:
    type: object
    description: "A map that defines the stage variables for the Stage resource that is associated with the new deployment. Variable names can have alphanumeric and underscore characters, and the values must match [A-Za-z0-9-._~:/?#&amp;=,]+."