---
description: 
pack: aws
enabled: true
entry_point: run.py
name: autoscaling_delete_notification_configuration
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: delete_notification_configuration
    immutable: true
    type: string
  cls:
    default: autoscaling
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  AutoScalingGroupName:
    type: string
    description: "The name of the Auto Scaling group."
    required: true
  TopicARN:
    type: string
    description: "The Amazon Resource Name (ARN) of the Amazon Simple Notification Service (SNS) topic."
    required: true