---
description: 
pack: aws
enabled: true
entry_point: run.py
name: batch_describe_compute_environments
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: describe_compute_environments
    immutable: true
    type: string
  cls:
    default: batch
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  computeEnvironments:
    type: array
    description: "A list of up to 100 compute environment names or full Amazon Resource Name (ARN) entries. "
  maxResults:
    type: integer
    description: "The maximum number of cluster results returned by DescribeComputeEnvironments in paginated output. When this parameter is used, DescribeComputeEnvironments only returns maxResults results in a single page along with a nextToken response element. The remaining results of the initial request can be seen by sending another DescribeComputeEnvironments request with the returned nextToken value. This value can be between 1 and 100. If this parameter is not used, then DescribeComputeEnvironments returns up to 100 results and a nextToken value if applicable."
  nextToken:
    type: string
    description: "The nextToken value returned from a previous paginated DescribeComputeEnvironments request where maxResults was used and the results exceeded the value of that parameter. Pagination continues from the end of the previous results that returned the nextToken value. This value is null when there are no more results to return.  This token should be treated as an opaque identifier that is only used to retrieve the next items in a list and not for other programmatic purposes. "