---
description: 
pack: aws
enabled: true
entry_point: run.py
name: batch_delete_compute_environment
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: delete_compute_environment
    immutable: true
    type: string
  cls:
    default: batch
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  computeEnvironment:
    type: string
    description: "The name or Amazon Resource Name (ARN) of the compute environment to delete. "
    required: true