---
description: 
pack: aws
enabled: true
entry_point: run.py
name: cloudfront_get_cloud_front_origin_access_identity_config
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: get_cloud_front_origin_access_identity_config
    immutable: true
    type: string
  cls:
    default: cloudfront
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  Id:
    type: string
    description: "The identity's ID. "
    required: true