---
description:
pack: aws
enabled: true
entry_point: run.py
name: codedeploy_continue_deployment
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: continue_deployment
    immutable: true
    type: string
  cls:
    default: codedeploy
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  deploymentId:
    type: string
    description: "The deployment ID of the blue/green deployment for which you want to start rerouting traffic to the replacement environment."
