---
description: 
pack: aws
enabled: true
entry_point: run.py
name: codedeploy_get_deployment
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: get_deployment
    immutable: true
    type: string
  cls:
    default: codedeploy
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  deploymentId:
    type: string
    description: "A deployment ID associated with the applicable IAM user or AWS account."
    required: true