---
description: 
pack: aws
enabled: true
entry_point: run.py
name: codedeploy_create_application
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: create_application
    immutable: true
    type: string
  cls:
    default: codedeploy
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  applicationName:
    type: string
    description: "The name of the application. This name must be unique with the applicable IAM user or AWS account."
    required: true