---
description: 
pack: aws
enabled: true
entry_point: run.py
name: codebuild_list_curated_environment_images
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: list_curated_environment_images
    immutable: true
    type: string
  cls:
    default: codebuild
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string