---
description: 
pack: aws
enabled: true
entry_point: run.py
name: codedeploy_get_application_revision
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: get_application_revision
    immutable: true
    type: string
  cls:
    default: codedeploy
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  applicationName:
    type: string
    description: "The name of the application that corresponds to the revision."
    required: true
  revision:
    type: object
    description: "Information about the application revision to get, including type and location."
    required: true