---
description: 
pack: aws
enabled: true
entry_point: run.py
name: codedeploy_stop_deployment
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: stop_deployment
    immutable: true
    type: string
  cls:
    default: codedeploy
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  deploymentId:
    type: string
    description: "The unique ID of a deployment."
    required: true
  autoRollbackEnabled:
    type: boolean
    description: "Indicates, when a deployment is stopped, whether instances that have been updated should be rolled back to the previous version of the application revision."