---
description: 
pack: aws
enabled: true
entry_point: run.py
name: config_describe_config_rule_evaluation_status
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: describe_config_rule_evaluation_status
    immutable: true
    type: string
  cls:
    default: config
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ConfigRuleNames:
    type: array
    description: "The name of the AWS managed Config rules for which you want status information. If you do not specify any names, AWS Config returns status information for all AWS managed Config rules that you use."
  NextToken:
    type: string
    description: "The NextToken string returned on a previous page that you use to get the next page of results in a paginated response."
  Limit:
    type: integer
    description: "The number of rule evaluation results that you want returned. This parameter is required if the rule limit for your account is more than the default of 50 rules. For more information about requesting a rule limit increase, see AWS Config Limits in the AWS General Reference Guide."