---
description: 
pack: aws
enabled: true
entry_point: run.py
name: config_put_configuration_recorder
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: put_configuration_recorder
    immutable: true
    type: string
  cls:
    default: config
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ConfigurationRecorder:
    type: object
    description: "The configuration recorder object that records each configuration change made to the resources."
    required: true