---
description: 
pack: aws
enabled: true
entry_point: run.py
name: config_start_config_rules_evaluation
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: start_config_rules_evaluation
    immutable: true
    type: string
  cls:
    default: config
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ConfigRuleNames:
    type: array
    description: "The list of names of Config rules that you want to run evaluations for."