---
description: 
pack: aws
enabled: true
entry_point: run.py
name: devicefarm_get_account_settings
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: get_account_settings
    immutable: true
    type: string
  cls:
    default: devicefarm
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string