---
description: 
pack: aws
enabled: true
entry_point: run.py
name: discovery_disassociate_configuration_items_from_application
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: disassociate_configuration_items_from_application
    immutable: true
    type: string
  cls:
    default: discovery
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  applicationConfigurationId:
    type: string
    description: "Configuration ID of an application from which each item will be disassociated."
    required: true
  configurationIds:
    type: array
    description: "Configuration ID of each item be be disassociated from an application."
    required: true