---
description: 
pack: aws
enabled: true
entry_point: run.py
name: discovery_update_application
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: update_application
    immutable: true
    type: string
  cls:
    default: discovery
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  configurationId:
    type: string
    description: "Configuration ID of the application to be updated."
    required: true
  name:
    type: string
    description: "New name of the application to be updated."
  description:
    type: string
    description: "New description of the application to be updated."