---
description: 
pack: aws
enabled: true
entry_point: run.py
name: discovery_create_application
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: create_application
    immutable: true
    type: string
  cls:
    default: discovery
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  name:
    type: string
    description: "Name of the application to be created."
    required: true
  description:
    type: string
    description: "Description of the application to be created."