---
description: 
pack: aws
enabled: true
entry_point: run.py
name: discovery_associate_configuration_items_to_application
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: associate_configuration_items_to_application
    immutable: true
    type: string
  cls:
    default: discovery
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  applicationConfigurationId:
    type: string
    description: "The configuration ID of an application with which items are to be associated."
    required: true
  configurationIds:
    type: array
    description: "The ID of each configuration item to be associated with an application."
    required: true