---
description: 
pack: aws
enabled: true
entry_point: run.py
name: discovery_delete_applications
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: delete_applications
    immutable: true
    type: string
  cls:
    default: discovery
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  configurationIds:
    type: array
    description: "Configuration ID of an application to be deleted."
    required: true