---
description: 
pack: aws
enabled: true
entry_point: run.py
name: ds_list_ip_routes
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: list_ip_routes
    immutable: true
    type: string
  cls:
    default: ds
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  DirectoryId:
    type: string
    description: "Identifier (ID) of the directory for which you want to retrieve the IP addresses."
    required: true
  NextToken:
    type: string
    description: "The ListIpRoutes.NextToken value from a previous call to ListIpRoutes. Pass null if this is the first call."
  Limit:
    type: integer
    description: "Maximum number of items to return. If this value is zero, the maximum number of items is specified by the limitations of the operation."