---
description: 
pack: aws
enabled: true
entry_point: run.py
name: elasticbeanstalk_describe_application_versions
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: describe_application_versions
    immutable: true
    type: string
  cls:
    default: elasticbeanstalk
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ApplicationName:
    type: string
    description: "Specify an application name to show only application versions for that application."
  VersionLabels:
    type: array
    description: "Specify a version label to show a specific application version."
  MaxRecords:
    type: integer
    description: "Specify a maximum number of application versions to paginate in the request."
  NextToken:
    type: string
    description: "Specify a next token to retrieve the next page in a paginated request."