---
description: 
pack: aws
enabled: true
entry_point: run.py
name: elasticbeanstalk_update_application
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: update_application
    immutable: true
    type: string
  cls:
    default: elasticbeanstalk
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ApplicationName:
    type: string
    description: "The name of the application to update. If no such application is found, UpdateApplication returns an InvalidParameterValue error. "
    required: true
  Description:
    type: string
    description: "A new description for the application. Default: If not specified, AWS Elastic Beanstalk does not update the description."