---
description: 
pack: aws
enabled: true
entry_point: run.py
name: elasticbeanstalk_create_application_version
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: create_application_version
    immutable: true
    type: string
  cls:
    default: elasticbeanstalk
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ApplicationName:
    type: string
    description: " The name of the application. If no application is found with this name, and AutoCreateApplication is false, returns an InvalidParameterValue error. "
    required: true
  VersionLabel:
    type: string
    description: "A label identifying this version. Constraint: Must be unique per application. If an application version already exists with this label for the specified application, AWS Elastic Beanstalk returns an InvalidParameterValue error. "
    required: true
  Description:
    type: string
    description: "Describes this version."
  SourceBuildInformation:
    type: object
    description: "Specify a commit in an AWS CodeCommit Git repository to use as the source code for the application version."
  SourceBundle:
    type: object
    description: "The Amazon S3 bucket and key that identify the location of the source bundle for this version.  The Amazon S3 bucket must be in the same region as the environment.  Specify a source bundle in S3 or a commit in an AWS CodeCommit repository (with SourceBuildInformation), but not both. If neither SourceBundle nor SourceBuildInformation are provided, Elastic Beanstalk uses a sample application."
  BuildConfiguration:
    type: object
    description: "Settings for an AWS CodeBuild build."
  AutoCreateApplication:
    type: boolean
    description: "Set to true to create an application with the specified name if it doesn't already exist."
  Process:
    type: boolean
    description: "Preprocesses and validates the environment manifest and configuration files in the source bundle. Validating configuration files can identify issues prior to deploying the application version to an environment."