---
description: 
pack: aws
enabled: true
entry_point: run.py
name: elasticbeanstalk_update_application_resource_lifecycle
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: update_application_resource_lifecycle
    immutable: true
    type: string
  cls:
    default: elasticbeanstalk
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ApplicationName:
    type: string
    description: "The name of the application."
    required: true
  ResourceLifecycleConfig:
    type: object
    description: "The lifecycle configuration."
    required: true