---
description: 
pack: aws
enabled: true
entry_point: run.py
name: elasticbeanstalk_create_application
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: create_application
    immutable: true
    type: string
  cls:
    default: elasticbeanstalk
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ApplicationName:
    type: string
    description: "The name of the application. Constraint: This name must be unique within your account. If the specified name already exists, the action returns an InvalidParameterValue error."
    required: true
  Description:
    type: string
    description: "Describes the application."
  ResourceLifecycleConfig:
    type: object
    description: "Specify an application resource lifecycle configuration to prevent your application from accumulating too many versions."