---
description: 
pack: aws
enabled: true
entry_point: run.py
name: elb_configure_health_check
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: configure_health_check
    immutable: true
    type: string
  cls:
    default: elb
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  LoadBalancerName:
    type: string
    description: "The name of the load balancer."
    required: true
  HealthCheck:
    type: object
    description: "The configuration information."
    required: true