---
description: 
pack: aws
enabled: true
entry_point: run.py
name: emr_describe_security_configuration
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: describe_security_configuration
    immutable: true
    type: string
  cls:
    default: emr
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  Name:
    type: string
    description: "The name of the security configuration."
    required: true