---
description: 
pack: aws
enabled: true
entry_point: run.py
name: gamelift_update_fleet_port_settings
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: update_fleet_port_settings
    immutable: true
    type: string
  cls:
    default: gamelift
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  FleetId:
    type: string
    description: "Unique identifier for the fleet you want to update port settings for."
    required: true
  InboundPermissionAuthorizations:
    type: array
    description: "Collection of port settings to be added to the fleet record."
  InboundPermissionRevocations:
    type: array
    description: "Collection of port settings to be removed from the fleet record."