---
description: 
pack: aws
enabled: true
entry_point: run.py
name: gamelift_describe_fleet_port_settings
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: describe_fleet_port_settings
    immutable: true
    type: string
  cls:
    default: gamelift
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  FleetId:
    type: string
    description: "Unique identifier for the fleet you want to retrieve port settings for."
    required: true