---
description:
pack: aws
enabled: true
entry_point: run.py
name: greengrass_create_deployment
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: create_deployment
    immutable: true
    type: string
  cls:
    default: greengrass
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  GroupId:
    type: string
    description: "The unique Id of the AWS Greengrass Group"
    required: true
  AmznClientToken:
    type: string
    description: "The client token used to request idempotent operations."
  DeploymentId:
    type: string
    description: "Id of the deployment if you wish to redeploy a previous deployment."
  DeploymentType:
    type: string
    description: "Type of deployment"
  GroupVersionId:
    type: string
    description: "Group Version you wish to deploy."
