---
description:
pack: aws
enabled: true
entry_point: run.py
name: greengrass_get_deployment_status
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: get_deployment_status
    immutable: true
    type: string
  cls:
    default: greengrass
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  DeploymentId:
    type: string
    description: "the deployment Id"
    required: true
  GroupId:
    type: string
    description: "The unique Id of the AWS Greengrass Group"
    required: true
