---
description: 
pack: aws
enabled: true
entry_point: run.py
name: kinesisanalytics_add_application_input
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: add_application_input
    immutable: true
    type: string
  cls:
    default: kinesisanalytics
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ApplicationName:
    type: string
    description: "Name of your existing Amazon Kinesis Analytics application to which you want to add the streaming source."
    required: true
  CurrentApplicationVersionId:
    type: integer
    description: "Current version of your Amazon Kinesis Analytics application. You can use the DescribeApplication operation to find the current application version."
    required: true
  Input:
    type: object
    description: ""
    required: true