---
description:
pack: aws
enabled: true
entry_point: run.py
name: kinesisanalytics_delete_application_cloud_watch_logging_option
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: delete_application_cloud_watch_logging_option
    immutable: true
    type: string
  cls:
    default: kinesisanalytics
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ApplicationName:
    type: string
    description: "The Amazon Kinesis Analytics application name."
    required: true
  CurrentApplicationVersionId:
    type: integer
    description: "The version ID of the Amazon Kinesis Analytics application."
    required: true
  CloudWatchLoggingOptionId:
    type: string
    description: "The CloudWatchLoggingOptionId of the CloudWatch logging option to delete. You can use the DescribeApplication operation to get the CloudWatchLoggingOptionId. "
    required: true
