---
description: 
pack: aws
enabled: true
entry_point: run.py
name: kinesisanalytics_list_applications
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: list_applications
    immutable: true
    type: string
  cls:
    default: kinesisanalytics
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  Limit:
    type: integer
    description: "Maximum number of applications to list."
  ExclusiveStartApplicationName:
    type: string
    description: "Name of the application to start the list with. When using pagination to retrieve the list, you don't need to specify this parameter in the first request. However, in subsequent requests, you add the last application name from the previous response to get the next page of applications."