---
description: 
pack: aws
enabled: true
entry_point: run.py
name: kinesisanalytics_delete_application_reference_data_source
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: delete_application_reference_data_source
    immutable: true
    type: string
  cls:
    default: kinesisanalytics
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ApplicationName:
    type: string
    description: "Name of an existing application."
    required: true
  CurrentApplicationVersionId:
    type: integer
    description: "Version of the application. You can use the DescribeApplication operation to get the current application version. If the version specified is not the current version, the ConcurrentModificationException is returned."
    required: true
  ReferenceId:
    type: string
    description: "ID of the reference data source. When you add a reference data source to your application using the AddApplicationReferenceDataSource, Amazon Kinesis Analytics assigns an ID. You can use the DescribeApplication operation to get the reference ID. "
    required: true