---
description: 
pack: aws
enabled: true
entry_point: run.py
name: kinesisanalytics_add_application_output
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: add_application_output
    immutable: true
    type: string
  cls:
    default: kinesisanalytics
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ApplicationName:
    type: string
    description: "Name of the application to which you want to add the output configuration."
    required: true
  CurrentApplicationVersionId:
    type: integer
    description: "Version of the application to which you want add the output configuration. You can use the DescribeApplication operation to get the current application version. If the version specified is not the current version, the ConcurrentModificationException is returned. "
    required: true
  Output:
    type: object
    description: "An array of objects, each describing one output configuration. In the output configuration, you specify the name of an in-application stream, a destination (that is, an Amazon Kinesis stream or an Amazon Kinesis Firehose delivery stream), and record the formation to use when writing to the destination."
    required: true