---
description: 
pack: aws
enabled: true
entry_point: run.py
name: kinesisanalytics_update_application
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: update_application
    immutable: true
    type: string
  cls:
    default: kinesisanalytics
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ApplicationName:
    type: string
    description: "Name of the Kinesis Analytics application to update."
    required: true
  CurrentApplicationVersionId:
    type: integer
    description: "The current application version ID. You can use the DescribeApplication operation to get this value."
    required: true
  ApplicationUpdate:
    type: object
    description: "Describes application updates."
    required: true