---
description:
pack: aws
enabled: true
entry_point: run.py
name: mturk_update_notification_settings
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: update_notification_settings
    immutable: true
    type: string
  cls:
    default: mturk
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  HITTypeId:
    type: string
    description: " The ID of the HIT type whose notification specification is being updated. "
    required: true
  Notification:
    type: object
    description: " The notification specification for the HIT type. "
  Active:
    type: boolean
    description: " Specifies whether notifications are sent for HITs of this HIT type, according to the notification specification. You must specify either the Notification parameter or the Active parameter for the call to UpdateNotificationSettings to succeed. "
