---
description: 
pack: aws
enabled: true
entry_point: run.py
name: pinpoint_update_application_settings
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: update_application_settings
    immutable: true
    type: string
  cls:
    default: pinpoint
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ApplicationId:
    type: string
    description: ""
    required: true
  WriteApplicationSettingsRequest:
    type: object
    description: ""
    required: true