---
description: 
pack: aws
enabled: true
entry_point: run.py
name: redshift_delete_hsm_configuration
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: delete_hsm_configuration
    immutable: true
    type: string
  cls:
    default: redshift
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  HsmConfigurationIdentifier:
    type: string
    description: "The identifier of the Amazon Redshift HSM configuration to be deleted."
    required: true