---
description: 
pack: aws
enabled: true
entry_point: run.py
name: s3_get_bucket_notification_configuration
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: get_bucket_notification_configuration
    immutable: true
    type: string
  cls:
    default: s3
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  Bucket:
    type: string
    description: "Name of the bucket to get the notification configuration for."
    required: true