---
description: 
pack: aws
enabled: true
entry_point: run.py
name: s3_put_bucket_metrics_configuration
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: put_bucket_metrics_configuration
    immutable: true
    type: string
  cls:
    default: s3
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  Bucket:
    type: string
    description: "The name of the bucket for which the metrics configuration is set."
    required: true
  Id:
    type: string
    description: "The ID used to identify the metrics configuration."
    required: true
  MetricsConfiguration:
    type: object
    description: "Specifies the metrics configuration."
    required: true