---
description: 
pack: aws
enabled: true
entry_point: run.py
name: ses_create_configuration_set
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: create_configuration_set
    immutable: true
    type: string
  cls:
    default: ses
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ConfigurationSet:
    type: object
    description: "A data structure that contains the name of the configuration set."
    required: true