---
description: 
pack: aws
enabled: true
entry_point: run.py
name: ses_update_configuration_set_event_destination
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: update_configuration_set_event_destination
    immutable: true
    type: string
  cls:
    default: ses
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ConfigurationSetName:
    type: string
    description: "The name of the configuration set that you want to update."
    required: true
  EventDestination:
    type: object
    description: "The event destination object that you want to apply to the specified configuration set."
    required: true