---
description: 
pack: aws
enabled: true
entry_point: run.py
name: ses_create_configuration_set_event_destination
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: create_configuration_set_event_destination
    immutable: true
    type: string
  cls:
    default: ses
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ConfigurationSetName:
    type: string
    description: "The name of the configuration set to which to apply the event destination."
    required: true
  EventDestination:
    type: object
    description: "An object that describes the AWS service to which Amazon SES will publish the email sending events associated with the specified configuration set."
    required: true