---
description: 
pack: aws
enabled: true
entry_point: run.py
name: ses_delete_configuration_set_event_destination
runner_type: python-script
parameters:
  account_id:
    type: string
  region:
    type: string
  action:
    default: delete_configuration_set_event_destination
    immutable: true
    type: string
  cls:
    default: ses
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  ConfigurationSetName:
    type: string
    description: "The name of the configuration set from which to delete the event destination."
    required: true
  EventDestinationName:
    type: string
    description: "The name of the event destination to delete."
    required: true