---
name: "test_rule"
enabled: true
trigger:
    type: "aws.test_sqs_new_message"
action:
    ref: "aws.test_ec2_start_instances"
    parameters:
        queue: "{{trigger.queue}}"
        InstanceIds: "{{trigger.body['InstanceIds']}}"