---
name: "test_rule"
enabled: true
trigger:
    type: "aws.sqs_new_message"
action:
    ref: "aws.ec2_describe_instances"
    parameters:
        environment: "{{trigger.environment}}"
        region: "{{trigger.region}}"
        InstanceIds: "{{trigger.body['InstanceIds']}}"
